### ISSUE TITLE
DSA-Stack-Python- Valid Parenthesis

### ISSUE THREAD

**Issue by jen-sjen** [ishangoyal13/fullstackDevelopment#114]
Hey there, I'm participating in #hactoberfest2k21, Please assign me the issue. Good day!
Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
An input string is valid if:
Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Example:
Input: s = "()[]{}"
Output: true

**Comment by ramnagane99** [comment]
you have to check small mistakes

**Comment by jen-sjen** [comment]
As in?

**Comment by jen-sjen** [comment]
Please merge my previous PR: #115 
issue: #56
So that I can go ahead with this PR  :)
