### ISSUE TITLE
Add a ToDo List Web Application

### ISSUE THREAD

**Issue by mustali17** [ishangoyal13/fullstackDevelopment#132]
please assign me this issue
here is the pull request--->  #129

**Comment by risav-sarkar** [comment]
Made a ToDo app using vanilla JS. #137

**Comment by Harshalngp** [comment]
Please assign this issue to me..

**Comment by therohit777** [comment]
I want to make web application please assign it to me

**Comment by therohit777** [comment]
Made ToDo Web Application using Html , Css and Vanilla Js.
Merge it. Todoapp_therohit777 #229
