### ISSUE TITLE
Singly Linked List - C++

### ISSUE THREAD

**Issue by SanskritiKushik5** [ishangoyal13/fullstackDevelopment#154]
Can I add the code for this (for hacktoberfest)?

**Comment by HackMEAny** [comment]
Singly linked list insetion is added here #183

**Comment by SanskritiKushik5** [comment]
Can I go with Doubly Linked List - Insertion, Deletion, Display, Search

**Comment by ishangoyal13** [comment]
> Can I go with Doubly Linked List - Insertion, Deletion, Display, Search?

Ya sure.. go ahead :)
