### ISSUE TITLE
[Create New Issue]: Add project -  CODERR website

### ISSUE THREAD

**Issue by rakbarca10** [ishangoyal13/fullstackDevelopment#353]
### Description

Description

Web Dev Projects 

I have added my project

### Language

Others

### Domain

Web Dev Projects

### Type of Contribution

Project

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by Shubham56-droid** [comment]
Can i add  web developement projects

**Comment by rakbarca10** [comment]
Yes you can

**Comment by Shubham56-droid** [comment]
i have added a pull request with a portfolio website pls do check it #446

**Comment by Shubham56-droid** [comment]
i have added a pull request with a restaurant website in web dev project folder pls do check it  #459
