### ISSUE TITLE
Remove Duplicates From the Sorted List

### ISSUE THREAD

**Issue by meghagupta19** [ishangoyal13/fullstackDevelopment#372]
### Description

Description:
Given the head of a sorted linked list, delete all nodes that have duplicate numbers, leaving only distinct numbers from the original list. Return the linked list sorted as well
Program-Link: https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii

### Language

C++

### Domain

Linked List

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by AnantDuhan** [comment]
/assign
only a PR is to be made by me
