### ISSUE TITLE
Operating Systems Concepts

### ISSUE THREAD

**Issue by avinash-218** [ishangoyal13/fullstackDevelopment#401]
### Description

Operating System Concepts like
- Producer Consumer Problem
- Inter process Communication using Shared Memory
- Inter process Communication using Pipes
- Page Replacement Algorithms
- Banker's Algorithm

### Language

C or C++

### Domain

Others

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by ishangoyal13** [comment]
> ### Description
> Operating System Concepts like
> 
> * Producer Consumer Problem
> * Inter process Communication using Shared Memory
> * Inter process Communication using Pipes
> * Page Replacement Algorithms
> * Banker's Algorithm
> 
> ### Language
> C++
> 
> ### Domain
> Others
> 
> ### Type of Contribution
> Code
> 
> ### Code of Conduct
> * [x]  I follow Contributing Guidelines & Code of conduct.

If possible kindly create a sub folder in c++ folder and name it aa OS Concept Codes.
