### ISSUE TITLE
[Create New Issue]: update README.md

### ISSUE THREAD

**Issue by 124015001** [ishangoyal13/fullstackDevelopment#457]
### Description

I will add link to Hacktoberfest's official website and their official discord channel.

### Language

Others

### Domain

Others

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by 124015001** [comment]
Assign this issue to me.

**Comment by ishangoyal13** [comment]
updating readme file is not allowed

**Comment by 124015001** [comment]
@ishangoyal13 Atleast see the pull request, I have made better changes.

**Comment by 124015001** [comment]
Also your repository has been excluded from the Hacktoberfest.
