### ISSUE TITLE
Hacktoberfest excluded project.

### ISSUE THREAD

**Issue by hiruthicShaSS** [ishangoyal13/fullstackDevelopment#473]
### Description

In hacktoberfest dashboard, the PR created for [ishangoyal13/Hacktoberfest2021](https://github.com/ishangoyal13/Hacktoberfest2021) is marked as "Excluded Project". If this is a mistake please look into it!
![image](https://user-images.githubusercontent.com/56349092/135608343-8c34be04-f994-4e2d-8426-eb0a4cc07ec7.png)

### Language

Python

### Domain

Others

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by aalimaslam** [comment]
Same is Problem With Me, I did Three Contributions to the Javascript Repository and i got the same error. Please Look into the matter

**Comment by ishangoyal13** [comment]
Try refreshing the hacktoberfest website. Let me know if this problem continues.

**Comment by aalimaslam** [comment]
Already Did Like 10 times

**Comment by ishangoyal13** [comment]
Wait for a while. Maybe servers are down. Many are getting "mature in 14 days" as a message on their PR.

**Comment by mustali17** [comment]
Yes facing same problem

**Comment by hiruthicShaSS** [comment]
> Wait for a while. Maybe servers are down. Many are getting "mature in 14 days" as a message on their PR. 

Yea, i was getting a lot of server internal errors on hactoberfest site. Maybe thats the issue. Seems like we need to create a PR to hactoberfest itself😅

**Comment by therohit777** [comment]
Yes I have the same problem , I made one contribution to it, now it showing excluded.
@ishangoyal13 brother please fix it out....

**Comment by ishangoyal13** [comment]
> > Wait for a while. Maybe servers are down. Many are getting "mature in 14 days" as a message on their PR.
> 
> Yea, i was getting a lot of server internal errors on hactoberfest site. Maybe thats the issue. Seems like we need to create a PR to hactoberfest itself😅

Please let me know when your PR show "mature in 14 days"

**Comment by ishangoyal13** [comment]
> Yes I have the same problem , I made one contribution to it, now it showing excluded. @ishangoyal13 brother please fix it out....

Working on it brother. Some people marked repository as spam because of 300+ PRs since morning.

**Comment by mustali17** [comment]
Any updates..... should we continue contributing on this repo...or should we move on to another repo...plz fill us with updates

**Comment by ishangoyal13** [comment]
Move on to another repo. This year all the repo named "Hacktoberfest" have been marked spam by community maintainers. 
Sorry for the blunder caused 😔

PRs of this repo will not count towards the fest

**Comment by hiruthicShaSS** [comment]
Aww, I am sorry to hear that😥. Anyways keep up the good work. 👍

**Comment by ishangoyal13** [comment]
> Aww, I am sorry to hear that😥. Anyways keep up the good work. 👍

I am really sorry that your efforts in making PRs to this repo goes somewhat worthless 🥺.  And one thing more.. all the repos named Hacktoberfest will be marked as spam soon.. try not to make PRs in further such repos 🤞
