### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by Mannuel25** [ishangoyal13/fullstackDevelopment#479]
### Description

This program generates a secure random password for you based on your preferences.

### Language

Python

### Domain

Others

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

Kindly assign this to me @ishangoyal13

**Comment by riyakushwaha** [comment]
Hii, Please assign this issue to me.

**Comment by Mannuel25** [comment]
> Hii, Please assign this issue to me.

I opened the issue to take it up, kindly open a new issue to add a different program or project.

**Comment by ishangoyal13** [comment]
> > Hii, Please assign this issue to me.
> 
> I opened the issue to take it up, kindly open a new issue to add a different program or project.

Due to spamming on my repo i was unable to see the issues. If you wiling to contribute to the repo kindly create a new issue and mention me in that. I will assign it to you

**Comment by Mannuel25** [comment]
> > > Hii, Please assign this issue to me.
> > 
> > 
> > I opened the issue to take it up, kindly open a new issue to add a different program or project.
> 
> Due to spamming on my repo i was unable to see the issues. If you wiling to contribute to the repo kindly create a new issue and mention me in that. I will assign it to you

Okay, I'm ready to take it up. Kindly assign this to me.
