### ISSUE TITLE
Generate all valid parenthesis

### ISSUE THREAD

**Issue by simran2607** [ishangoyal13/fullstackDevelopment#482]
### Description

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.
Example 1:
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]

### Language

C++

### Domain

Backtracking

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by iamsunil25** [comment]
@simran2607  i want to work on this issue

**Comment by simran2607** [comment]
> @simran2607 i want to work on this issue

Already created the pull request for the same. You may create new issue and work on that. Happy coding. :-)
