### ISSUE TITLE
Trapping rain water

### ISSUE THREAD

**Issue by yogesh-kansal** [ishangoyal13/fullstackDevelopment#488]
### Description

Description
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

 

### Language

C++

### Domain

Stacks

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by yogesh-kansal** [comment]
Hii there I want ot contrubute to this problem.
please assgin it to me.

**Comment by SleepyAryan** [comment]
can i contribute this
