### ISSUE TITLE
[Create New Issue]: Excluded Project

### ISSUE THREAD

**Issue by jen-sjen** [ishangoyal13/fullstackDevelopment#508]
### Description

Hey, I have had 2 successful PRs on this repository, but on the main webpage initially it was showing "matures in 14 days", but now it's showing "excluded Project". Any idea what's the issue?

### Language

Others

### Domain

Others

### Type of Contribution

Project

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by geromegrignon** [comment]
Hey @jen-sjen, Hacktoberfest official organization ban repositories that don't follow the values of Hacktoberfest.
