### ISSUE TITLE
Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by Rutikab12** [ishangoyal13/fullstackDevelopment#545]
### Description

Program: Given an array, each element represents the height of the histograms bar, and the width of each bar is 1, find the area of the largest rectangle in the histogram.

In C++ language as Hacktoberfest21 participant.

### Language

C++

### Domain

Stacks

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by iamsunil25** [comment]
@Rutikab12  i am working on this issue

**Comment by Rutikab12** [comment]
> @Rutikab12 i am working on this issue

Okay.
