### ISSUE TITLE
Hacktoberfest Excluded Repo?!?

### ISSUE THREAD

**Issue by dahiya-code** [ishangoyal13/fullstackDevelopment#550]
### Description

On my profile your repo contributions have suddenly been marked as EXCLUDED
Attaching screenshot for the same
![image](https://user-images.githubusercontent.com/67997492/135627147-773c2b42-fbd5-4189-96cd-b50335c129cf.png)

### Language

C++

### Domain

Dynamic Programming

### Type of Contribution

Project

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by ishangoyal13** [comment]
Due to more than 300+ PRs since morning, hacktoberfest maintainers thought this is spam repo and marked this repo as spam. 
sorry for the cause 😓

**Comment by suvanbalu** [comment]
> Due to more than 300+ PRs since morning, hacktoberfest maintainers thought this is spam repo and marked this repo as spam. sorry for the cause 😓

Will they include the project again?

**Comment by anonsecteaminc** [comment]
Acc
